parameters:
    nurschool_mailer:
        api_key: '%env(SENDGRID_API_KEY)%'
        sandbox: '%env(bool:SENDGRID_SANDBOX_MODE)%'
        disable_delivery: '%env(bool:MAILER_DISABLE_DELIVERY)%' # default false
        redirect_to: '%env(MAILER_REDIRECT_TO)%' # default false
        default_address: '%env(resolve:MAILER_DEFAULT_ADDRESS)%'
        default_name: '%env(resolve:MAILER_DEFAULT_NAME)%'
        welcome:
            template: '%env(resolve:SENDGRID_CONFIRMATION_TEMPLATE_ID)%'
            subject: 'Welcome to Nurschool'
        resetting:
            template: '%env(resolve:SENDGRID_RESETTING_TEMPLATE_ID)%'
            subject: 'Reset your password'
        invitation:
            template: '%env(resolve:SENDGRID_INVITATION_TEMPLATE_ID)%'
            subject: 'Invitation to join to Nurschool'

services:
    nurschool.mailer:
        class: Nurschool\Shared\Infrastructure\Email\SendGrid\SendGridMailer