api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Entity'
            - '%kernel.project_dir%/src/Forum/Infrastructure/Persistence/Doctrine/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
