easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
        - Nurschool\Entity\User
        - Nurschool\Entity\Enquiry
        - Nurschool\Entity\School