framework:
    messenger:
        default_bus: messenger.bus.command
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        buses:
            messenger.bus.command:
                middleware:
                    - validation
                    - doctrine_transaction

            messenger.bus.query:
                middleware:
                    - validation

            messenger.bus.event:
                # the 'allow_no_handlers' middleware allows to have no handler
                # configured for this bus without throwing an exception
                default_middleware: allow_no_handlers
                middleware:
                    - validation

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
#            'Nurschool\Shared\Application\Command\Command': async
            'Nurschool\Shared\Application\Command\Command': sync
            'Nurschool\Shared\Domain\Event\DomainEvent': async
            'Nurschool\Shared\Application\Query\Query': sync