security:
    enable_authenticator_manager: true

    providers:
        users:
            entity:
                # the class of the entity that represents users
                class: Nurschool\User\Domain\User
                # the property to query by - e.g. username, email, etc
                property: 'email.value'

    firewalls:
        main:
            lazy: true
            custom_authenticator: Nurschool\Security\LoginFormAuthenticator
            logout:
                path: logout
                # where to redirect after logout
                # target: app_any_route

