twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['@EasyAdmin/crud/form_theme.html.twig']
    globals:
        version: '%env(resolve:APP_VERSION)%'
