vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: '%nurschool.path.user_images%'
            upload_destination: '%kernel.project_dir%/public%nurschool.path.user_images%'
            namer:
                service: Nurschool\File\Uploader\Naming\UniqidNamer
                options: { delete_extension: true }

        school_images:
            uri_prefix: '%nurschool.path.school_images%'
            upload_destination: '%kernel.project_dir%/public%nurschool.path.school_images%'
            namer:
                service: Nurschool\File\Uploader\Naming\UniqidNamer
                options: { delete_extension: true }