# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        Nurschool\Common\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        Nurschool\Common\Application\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        Nurschool\Common\Domain\Event\DomainEventListener:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Nurschool\Platform\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Symfony/DependencyInjection/'
            - '../src/Infrastructure/Symfony/Kernel.php'

    Nurschool\Platform\Infrastructure\Symfony\Api\Action\:
        resource: '../src/Infrastructure/Symfony/Api/Action/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Nurschool\Platform\Domain\Repository\UserStoreRepository: '@Nurschool\Platform\Infrastructure\Persistence\Doctrine\Repository\UserStoreDoctrineRepository'
    Nurschool\Common\Application\Command\CommandBus: '@Nurschool\Platform\Infrastructure\Symfony\Bus\Command\SymfonyCommandBus'
    Nurschool\Common\Domain\Event\DomainEventDispatcher: '@Nurschool\Platform\Infrastructure\Symfony\Bus\Event\RabbitMqDomainEventDispatcher'
    
    Nurschool\Common\Infrastructure\Url\UriSigner:
        arguments: [ '%kernel.secret%', 'signature' ]

    Nurschool\Common\Application\Url\SignService:
        arguments:
            - '%kernel.secret%'
            - '@Nurschool\Common\Infrastructure\Url\UriSigner'

    Nurschool\Platform\Infrastructure\Symfony\Storage\LocalFileStorage:
        arguments: [ '%kernel.project_dir%' ]

    Nurschool\Platform\Infrastructure\Avatar\LetterAvatarGenerator:
        arguments: [ '@Nurschool\Platform\Infrastructure\Symfony\Storage\LocalFileStorage' ]