# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Nurschool\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    Nurschool\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Nurschool\Storage\UserStorage:
        arguments: ["@fos_user.util.password_updater", "@fos_user.util.canonical_fields_updater", "@doctrine.orm.entity_manager", "%fos_user.model.user.class%"]

    Nurschool\Form\Type\RegistrationFormType:
        arguments: ["@router", "%fos_user.model.user.class%"]

#    Nurschool\Controller\RegistrationController:
#        decorates: fos_user.registration.controller
#        arguments:
#            - '@Nurschool\Controller\RegistrationController.inner'
##            - '@EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext'
#            - '@event_dispatcher'
#            - '@fos_user.registration.form.factory'
#            - '@fos_user.user_manager'
##            - '@fos_user.listener.authentication'
##            - '@fos_user.listener.flash'
##            - '@App\Media\AvatarManager'
##            - '@translator'
#        tags: ['controller.service_arguments']